### ISSUE TITLE
setWindowTitle无效

### ISSUE THREAD

**Issue by yangweijie** [easysoft/phpsciter#1]
![image](https://user-images.githubusercontent.com/1614114/99935110-df547600-2d9a-11eb-87c1-4cfcc7f0e68c.png)

**Comment by LeiZhang-Hunter** [comment]
收到我这边会尽快修复

**Comment by LeiZhang-Hunter** [comment]
您好，针对您的问题，我已经花时间修复，新的dll库可以到

**Comment by LeiZhang-Hunter** [comment]
您的问题我已经修复，新的dll库可以到

**Comment by LeiZhang-Hunter** [comment]
您的dll库我已经修复，新的dll库版本可以到 （https://github.com/longyan/phpsciter/tree/master/lib/extension/windows/php-7.4.6-nts-Win32-vc15-x64/x64）这里去下载最新的dll库，注意最好是要使用php7.4的版本，感谢您的使用

**Comment by LeiZhang-Hunter** [comment]
您的dll库我已经修复，新的dll库版本可以到 
（https://github.com/longyan/phpsciter/blob/master/lib/extension/windows/php-7.4.6-nts-Win32-vc15-x64/x64/phpsciter.dll）
这里去下载最新的dll库，注意最好是要使用php7.4的版本，感谢您的使用
