### ISSUE TITLE
部分语法 没有文档

### ISSUE THREAD

**Issue by yangweijie** [easysoft/phpsciter#3]
![image](https://user-images.githubusercontent.com/1614114/100052970-0b82fc00-2e5a-11eb-8afc-8057402e585b.png)
![image](https://user-images.githubusercontent.com/1614114/100052998-16d62780-2e5a-11eb-9010-4fd31904eb86.png)
这些不是标准的html 和js语法 有没有官方文档说明的地方 load-frame 的几个按钮点了 除了“load html” 按钮点了可以有响应 其他按钮点了 报错  help browser 打开弹得是白页

**Comment by easysoft** [comment]
是用的tiscript。可以参考sciter官方的文档。和js差不多，有一些改动和增强。
作者正在做sciter-js.sdk，集成的是quickjs引擎。值得期待。
