### ISSUE TITLE
macOS 编译后加载 .so 文件有点问题

### ISSUE THREAD

**Issue by teg1c** [easysoft/phpsciter#5]

**Comment by teg1c** [comment]
![image](https://user-images.githubusercontent.com/27796058/106545097-b3e0cb00-6543-11eb-8ce9-99bbcb281841.png)

`/usr/local/lib/php/pecl/20190902/` 目录下确实是有 `phpsciter.so` 文件的

**Comment by LeiZhang-Hunter** [comment]
> ![image](https://user-images.githubusercontent.com/27796058/106545097-b3e0cb00-6543-11eb-8ce9-99bbcb281841.png)
> 
> `/usr/local/lib/php/pecl/20190902/` 目录下确实是有 `phpsciter.so` 文件的

好的 我近期修复一下

**Comment by LeiZhang-Hunter** [comment]
> ![image](https://user-images.githubusercontent.com/27796058/106545097-b3e0cb00-6543-11eb-8ce9-99bbcb281841.png)
> 
> `/usr/local/lib/php/pecl/20190902/` 目录下确实是有 `phpsciter.so` 文件的

您好符号链接问题已经修复，请你再重新编译一下。

**Comment by teg1c** [comment]
还是有问题
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'phpsciter.so' (tried: /usr/local/lib/php/pecl/20190902/phpsciter.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so, 9): Library not loaded: /usr/local/lib/sciter-osx-64.dylib
  Referenced from: /usr/local/lib/php/pecl/20190902/phpsciter.so
  Reason: image not found), /usr/local/lib/php/pecl/20190902/phpsciter.so.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'phpsciter.so' (tried: /usr/local/lib/php/pecl/20190902/phpsciter.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so, 9): Library not loaded: /usr/local/lib/sciter-osx-64.dylib
  Referenced from: /usr/local/lib/php/pecl/20190902/phpsciter.so
  Reason: image not found), /usr/local/lib/php/pecl/20190902/phpsciter.so.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so.so, 9): image not found)) in Unknown on line 0
```

**Comment by teg1c** [comment]
@

> 还是有问题
> 
> ```
> PHP Warning:  PHP Startup: Unable to load dynamic library 'phpsciter.so' (tried: /usr/local/lib/php/pecl/20190902/phpsciter.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so, 9): Library not loaded: /usr/local/lib/sciter-osx-64.dylib
>   Referenced from: /usr/local/lib/php/pecl/20190902/phpsciter.so
>   Reason: image not found), /usr/local/lib/php/pecl/20190902/phpsciter.so.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so.so, 9): image not found)) in Unknown on line 0
> 
> Warning: PHP Startup: Unable to load dynamic library 'phpsciter.so' (tried: /usr/local/lib/php/pecl/20190902/phpsciter.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so, 9): Library not loaded: /usr/local/lib/sciter-osx-64.dylib
>   Referenced from: /usr/local/lib/php/pecl/20190902/phpsciter.so
>   Reason: image not found), /usr/local/lib/php/pecl/20190902/phpsciter.so.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so.so, 9): image not found)) in Unknown on line 0
> ```

@LeiZhang-Hunter

**Comment by LeiZhang-Hunter** [comment]
可以加我微信zl357733652



---原始邮件---
发件人: "tegic"<notifications@github.com&gt;
发送时间: 2021年2月21日(周日) 晚上6:05
收件人: "longyan/phpsciter"<phpsciter@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"zhanglei"<357733652@qq.com&gt;;
主题: Re: [longyan/phpsciter] macOS 编译后加载 .so 文件有点问题 (#5)




 
@
  
还是有问题
 PHP Warning:  PHP Startup: Unable to load dynamic library 'phpsciter.so' (tried: /usr/local/lib/php/pecl/20190902/phpsciter.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so, 9): Library not loaded: /usr/local/lib/sciter-osx-64.dylib   Referenced from: /usr/local/lib/php/pecl/20190902/phpsciter.so   Reason: image not found), /usr/local/lib/php/pecl/20190902/phpsciter.so.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so.so, 9): image not found)) in Unknown on line 0 Warning: PHP Startup: Unable to load dynamic library 'phpsciter.so' (tried: /usr/local/lib/php/pecl/20190902/phpsciter.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so, 9): Library not loaded: /usr/local/lib/sciter-osx-64.dylib   Referenced from: /usr/local/lib/php/pecl/20190902/phpsciter.so   Reason: image not found), /usr/local/lib/php/pecl/20190902/phpsciter.so.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so.so, 9): image not found)) in Unknown on line 0   
@LeiZhang-Hunter

**Comment by LeiZhang-Hunter** [comment]
> @
> 
> > 还是有问题
> > ```
> > PHP Warning:  PHP Startup: Unable to load dynamic library 'phpsciter.so' (tried: /usr/local/lib/php/pecl/20190902/phpsciter.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so, 9): Library not loaded: /usr/local/lib/sciter-osx-64.dylib
> >   Referenced from: /usr/local/lib/php/pecl/20190902/phpsciter.so
> >   Reason: image not found), /usr/local/lib/php/pecl/20190902/phpsciter.so.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so.so, 9): image not found)) in Unknown on line 0
> > 
> > Warning: PHP Startup: Unable to load dynamic library 'phpsciter.so' (tried: /usr/local/lib/php/pecl/20190902/phpsciter.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so, 9): Library not loaded: /usr/local/lib/sciter-osx-64.dylib
> >   Referenced from: /usr/local/lib/php/pecl/20190902/phpsciter.so
> >   Reason: image not found), /usr/local/lib/php/pecl/20190902/phpsciter.so.so (dlopen(/usr/local/lib/php/pecl/20190902/phpsciter.so.so, 9): image not found)) in Unknown on line 0
> > ```
> 
> @LeiZhang-Hunter

已经修复
